from typing import Any, Iterator

class _metaX(type):
    def __getattr__(self, name: str) -> X: ...
    def __iter__(self) -> Iterator[tuple[str, tuple[Any, ...], dict[str, Any]]]: ...
    def __len__(self) -> int: ...
    def __repr__(self) -> str: ...
    def __call__(self, *args: Any, **kwargs: Any) -> X: ...
    def __getitem__(self, key: Any) -> X: ...
    def __add__(self, other: Any) -> X: ...
    def __sub__(self, other: Any) -> X: ...
    def __mul__(self, other: Any) -> X: ...
    def __matmul__(self, other: Any) -> X: ...
    def __truediv__(self, other: Any) -> X: ...
    def __floordiv__(self, other: Any) -> X: ...
    def __mod__(self, other: Any) -> X: ...
    def __divmod__(self, other: Any) -> X: ...
    def __pow__(self, other: Any) -> X: ...
    def __lshift__(self, other: Any) -> X: ...
    def __rshift__(self, other: Any) -> X: ...
    def __and__(self, other: Any) -> X: ...
    def __or__(self, other: Any) -> X: ...
    def __xor__(self, other: Any) -> X: ...
    def __radd__(self, other: Any) -> X: ...
    def __rsub__(self, other: Any) -> X: ...
    def __rmul__(self, other: Any) -> X: ...
    def __rmatmul__(self, other: Any) -> X: ...
    def __rtruediv__(self, other: Any) -> X: ...
    def __rfloordiv__(self, other: Any) -> X: ...
    def __rmod__(self, other: Any) -> X: ...
    def __rdivmod__(self, other: Any) -> X: ...
    def __rpow__(self, other: Any) -> X: ...
    def __rlshift__(self, other: Any) -> X: ...
    def __rrshift__(self, other: Any) -> X: ...
    def __rand__(self, other: Any) -> X: ...
    def __ror__(self, other: Any) -> X: ...
    def __rxor__(self, other: Any) -> X: ...

    def __neg__(self) -> X: ...
    def __pos__(self) -> X: ...
    def __abs__(self) -> X: ...
    def __invert__(self) -> X: ...
    def __round__(self) -> X: ...
    def __trunc__(self) -> X: ...
    def __floor__(self) -> X: ...
    def __ceil__(self) -> X: ...

class X(metaclass=_metaX):
    def __getattr__(self, name: str) -> X: ...
    def __iter__(self) -> Iterator[tuple[str, tuple[Any, ...], dict[str, Any]]]: ...
    def __len__(self) -> int: ...
    def __repr__(self) -> str: ...
    def __call__(self, *args: Any, **kwargs: Any) -> X: ...
    def __getitem__(self, key: Any) -> X: ...
    def __add__(self, other: Any) -> X: ...
    def __sub__(self, other: Any) -> X: ...
    def __mul__(self, other: Any) -> X: ...
    def __matmul__(self, other: Any) -> X: ...
    def __truediv__(self, other: Any) -> X: ...
    def __floordiv__(self, other: Any) -> X: ...
    def __mod__(self, other: Any) -> X: ...
    def __divmod__(self, other: Any) -> X: ...
    def __pow__(self, other: Any) -> X: ...
    def __lshift__(self, other: Any) -> X: ...
    def __rshift__(self, other: Any) -> X: ...
    def __and__(self, other: Any) -> X: ...
    def __or__(self, other: Any) -> X: ...
    def __xor__(self, other: Any) -> X: ...
    def __radd__(self, other: Any) -> X: ...
    def __rsub__(self, other: Any) -> X: ...
    def __rmul__(self, other: Any) -> X: ...
    def __rmatmul__(self, other: Any) -> X: ...
    def __rtruediv__(self, other: Any) -> X: ...
    def __rfloordiv__(self, other: Any) -> X: ...
    def __rmod__(self, other: Any) -> X: ...
    def __rdivmod__(self, other: Any) -> X: ...
    def __rpow__(self, other: Any) -> X: ...
    def __rlshift__(self, other: Any) -> X: ...
    def __rrshift__(self, other: Any) -> X: ...
    def __rand__(self, other: Any) -> X: ...
    def __ror__(self, other: Any) -> X: ...
    def __rxor__(self, other: Any) -> X: ...

    def __neg__(self) -> X: ...
    def __pos__(self) -> X: ...
    def __abs__(self) -> X: ...
    def __invert__(self) -> X: ...
    def __round__(self) -> X: ...
    def __trunc__(self) -> X: ...
    def __floor__(self) -> X: ...
    def __ceil__(self) -> X: ...
